-- ════════════════════════════════════════════════════════════════
-- 03_fact_table.sql
-- Create the fact_sales table
-- One row per PC sale transaction
-- Contains all measures + foreign keys to all 6 dimension tables
-- Run AFTER 02_dim_tables.sql
-- ════════════════════════════════════════════════════════════════

CREATE TABLE warehouse.fact_sales (
    -- Surrogate key
    sale_id                  SERIAL          PRIMARY KEY,

    -- Foreign keys → dimension tables
    shop_key                 INT             REFERENCES warehouse.dim_shop(shop_key),
    product_key              INT             REFERENCES warehouse.dim_product(product_key),
    customer_key             INT             REFERENCES warehouse.dim_customer(customer_key),
    salesperson_key          INT             REFERENCES warehouse.dim_salesperson(salesperson_key),
    date_key                 DATE            REFERENCES warehouse.dim_date(date_key),
    ship_date_key            DATE            REFERENCES warehouse.dim_date(date_key),
    junk_key                 INT             REFERENCES warehouse.dim_junk(junk_key),

    -- Measures — the numbers analysts SUM, AVG, COUNT
    cost_price               DECIMAL(10,2),
    sale_price               DECIMAL(10,2),
    discount_amount          DECIMAL(10,2)   DEFAULT 0,
    finance_amount           DECIMAL(10,2)   DEFAULT 0,
    cost_of_repairs          DECIMAL(10,2)   DEFAULT 0,
    total_sales_per_employee DECIMAL(10,2),

    -- Calculated measures — derived at load time
    gross_profit             DECIMAL(10,2)   GENERATED ALWAYS AS
                             (sale_price - cost_price) STORED,
    net_profit               DECIMAL(10,2)   GENERATED ALWAYS AS
                             (sale_price - cost_price - discount_amount) STORED,
    profit_margin_pct        DECIMAL(5,2)    GENERATED ALWAYS AS
                             (ROUND((sale_price - cost_price - discount_amount)
                              / NULLIF(sale_price, 0) * 100, 2)) STORED,

    -- Audit
    loaded_at                TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for faster JOIN performance
CREATE INDEX idx_fact_sales_shop        ON warehouse.fact_sales(shop_key);
CREATE INDEX idx_fact_sales_product     ON warehouse.fact_sales(product_key);
CREATE INDEX idx_fact_sales_customer    ON warehouse.fact_sales(customer_key);
CREATE INDEX idx_fact_sales_salesperson ON warehouse.fact_sales(salesperson_key);
CREATE INDEX idx_fact_sales_date        ON warehouse.fact_sales(date_key);
CREATE INDEX idx_fact_sales_ship_date   ON warehouse.fact_sales(ship_date_key);
CREATE INDEX idx_fact_sales_junk        ON warehouse.fact_sales(junk_key);

COMMENT ON TABLE  warehouse.fact_sales                        IS 'One row per PC sale. Contains measures and foreign keys to all dimensions.';
COMMENT ON COLUMN warehouse.fact_sales.sale_id                IS 'Surrogate primary key — generated by warehouse';
COMMENT ON COLUMN warehouse.fact_sales.shop_key               IS 'FK → dim_shop — where the sale happened';
COMMENT ON COLUMN warehouse.fact_sales.product_key            IS 'FK → dim_product — what PC was sold';
COMMENT ON COLUMN warehouse.fact_sales.customer_key           IS 'FK → dim_customer — who bought the PC';
COMMENT ON COLUMN warehouse.fact_sales.salesperson_key        IS 'FK → dim_salesperson — who made the sale';
COMMENT ON COLUMN warehouse.fact_sales.date_key               IS 'FK → dim_date — when the sale happened (purchase date)';
COMMENT ON COLUMN warehouse.fact_sales.ship_date_key          IS 'FK → dim_date — when the PC was shipped (role-playing dimension)';
COMMENT ON COLUMN warehouse.fact_sales.junk_key               IS 'FK → dim_junk — how the sale happened (payment, channel, priority)';
COMMENT ON COLUMN warehouse.fact_sales.cost_price             IS 'What the shop paid for the PC';
COMMENT ON COLUMN warehouse.fact_sales.sale_price             IS 'What the customer paid for the PC';
COMMENT ON COLUMN warehouse.fact_sales.discount_amount        IS 'Discount given on this sale';
COMMENT ON COLUMN warehouse.fact_sales.finance_amount         IS 'Amount financed if customer used finance option';
COMMENT ON COLUMN warehouse.fact_sales.cost_of_repairs        IS 'Repair costs associated with this sale';
COMMENT ON COLUMN warehouse.fact_sales.gross_profit           IS 'Calculated: sale_price - cost_price';
COMMENT ON COLUMN warehouse.fact_sales.net_profit             IS 'Calculated: sale_price - cost_price - discount_amount';
COMMENT ON COLUMN warehouse.fact_sales.profit_margin_pct      IS 'Calculated: net_profit / sale_price * 100';

-- Verify full star schema
SELECT
    t.table_name,
    COUNT(c.column_name)     AS columns,
    obj_description(
        ('"warehouse"."' || t.table_name || '"')::regclass, 'pg_class'
    )                        AS description
FROM information_schema.tables  t
JOIN information_schema.columns c
    ON  t.table_name   = c.table_name
    AND t.table_schema = c.table_schema
WHERE t.table_schema = 'warehouse'
GROUP BY t.table_name
ORDER BY t.table_name;
